### ISSUE TITLE
Not able to view react native stories on web

### ISSUE THREAD

**Issue by rajatrao777** [storybookjs/design-system#138]
Hi ,
First of all storybook is amazing!.
I am trying to use it for building design system library for react-native.
I have installed react-native through react-native init and configured storybook through sb init
On running storybook server, i am able to view default stories on mobile device but web shows default stories but on selecting it changes in mobile and view is not there in web
![sb](https://user-images.githubusercontent.com/22995576/71449218-8d603600-276e-11ea-8b34-09668c5fa2f9.png)
Since i want to share the design stories with others and viewable on site (final deploy)
What is the general process to view react native stories on mobile(this is working fine) as well as web view as i do not find any solution :disappointed: 
I have gone through this below issues and tried configuring but does not help and i need some proper configuration even after future update of sb
Please advise on this situation.
[one](https://github.com/storybookjs/storybook/issues/5821)
[two](https://github.com/storybookjs/storybook/issues/1946)
[three](https://github.com/storybookjs/storybook/issues/3353)
Below version
"react": "16.9.0",
"react-native": "0.61.5",
 "@storybook/addon-actions": "^5.2.8",
 "@storybook/addon-links": "^5.2.8",
 "@storybook/addons": "^5.2.8",
 "@storybook/react-native": "^5.2.8",
 "@storybook/react-native-server": "^5.2.8"
storybook version :- 5.2.8

**Comment by kylesuss** [comment]
Hey @rajatrao777 -- I am going to close this issue in this repo. I see that you also created an issue in the `storybook` project -- that is the right place for your question. I have also copied over your question form here so that all of the context is there: https://github.com/storybookjs/storybook/issues/9247

This repo is a specific project to create shareable components for Storybook web properties, and not a repo for general design system topics related to Storybook! Good luck 😄

**Comment by rajatrao777** [comment]
Hi @kylesuss  Sorry for the trouble ...will keep in mind :100:
