### ISSUE TITLE
Fix tooltip hover issue

### ISSUE THREAD

**Issue by kylesuss** [storybookjs/design-system#82]
Sometimes the tooltip can have issues where when you try to hover over the dropdown, it disappears instantly:

![tooltip](https://user-images.githubusercontent.com/3035355/66222560-ad5fec00-e68e-11e9-858c-d7eb284eb164.gif)

Maybe the hover target is too small?

**Comment by domyen** [comment]
I think this is happening because the hiding is happening instantly once you're out of the tooltip target boundary. That means users realistically have a 1px wide bridge to the tooltip contents if they want to click inside.

We might be able to resolve this with [`delayHide`](https://github.com/mohsinulhaq/react-popper-tooltip#delayhide) to delay hiding the tooltip for some number of milliseconds (70ms?) to give users time to navigate their cursors to the tooltip.

**Comment by kylesuss** [comment]
:rocket: Issue was released in v1.1.0 :rocket:
